### ISSUE TITLE
Add Chamber of Deputies request for information

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/jarbas#119] opened 2017-01-13 18:24 UTC
Since we've being auditing some suspicious cases found by Rosie, it would be nice if we could see information related to requests we made to the Chamber of Deputies like protocol number and status on Jarbas front-end. In that way we can see whether or not one document has an request open.

**Comment by cuducos** [comment] 2017-01-13 18:46
It looks like a great idea, but I still have my doubts about how to organize all the information.

By now we report the cases ourselves, but this is not suppose to be like that in the medium and long-term. So how to keep track of what was reported in an ideal future where anyone can spot something on Jarbas and report ir to the Chamber of Deputies?

Another thing to consider is that the Chamber of Deputies removes from the XML (the raw source for data) reimbursements reported and confirmed as irregular. By design Jarbas (and Rosie) will lost track of these reimbursements — i.e. reimbursements reported and confirmed as irregular would disappear from Jarbas.

The protocol is kind of useless because I guess (yes, it's just a guess) that they are only accessible by the account who made the report. But this itself is a minor detail.

The point is: we have to give a step back and discuss from the design part of view the two major topics I raised:

1. How to keep track of reports when anyone can actually report?
2. How to keep track of reimbursements removed/edited in the XML?

It's not impossible, specially point 2 is kind of easy to implement — so I'll add a third one: how to prioritize this among every other issue we have in Serenata as a whole?

I think those are the real questions ; )

**Comment by jtemporal** [comment] 2017-01-13 18:49
Well said @cuducos we need to discuss all of this better ;)

**Comment by cabral** [comment] 2017-01-22 15:41
Maybe we break the questions 1,2,3 with a issue # for each and invite people from the tech group to discuss them in the issue stream?

**Comment by cuducos** [comment] 2017-05-11 16:38
Closing this as our strategy doesn't count on reporting to the Chamber of Deputies anymore.

**Closed by cuducos** 2017-05-11 16:38 UTC
Labels: question
